name = "travellingtheworld"
compatibility_date = "2025-07-31"

# Pages uses this instead of [assets]
pages_build_output_dir = "./public"

# Pages uses this instead of [build]
build_command = "chmod a+x build.sh && ./build.sh"